Small.Data.Web/Models/NoteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace Small.Data.Web.Models
{
	public class NoteViewModel
	{
		[Display(Name = "Name")]
		public string Name { get; set; }

		[Display(Name = "Detail")]
		public string Detail { get; set; }


		[Display(Name = "Category")]
		public string Category { get; set; }

		public int NoteID { get; set; }
	}
}

Small.Data.Web/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Small.Data.Dat;
using Small.Data.Web.Models;

namespace Small.Data.Web.Controllers
{
    public class NoteController : Controller
    {
        //
        // GET: /Note/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Note/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Note/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Note/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Note/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Note/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Note/Delete/5
 
        public ActionResult Delete(int id)
        {
			NoteDao noteDao = new NoteDao();
			noteDao.Delete(id);

			return RedirectToAction("List");
        }

        //
        // POST: /Note/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
				NoteDao noteDao = new NoteDao();
				noteDao.Delete(id);
 
                return RedirectToAction("List");
            }
            catch
            {
                return null;
            }
        }

		//
		// GET: /Note/Save

		public ActionResult Save()
		{
			return View();
		} 

		[HttpPost]
		public ActionResult Save(NoteViewModel note)
		{
			try
			{
				if (!String.IsNullOrEmpty(note.Detail))
				{
					NoteDao noteDao = new NoteDao();
					Blt.Note myNote = new Blt.Note();

					myNote.Name = note.Name;
					myNote.Detail = note.Detail;
					myNote.Category = note.Category;

					noteDao.Insert(myNote);

				}
				return RedirectToAction("List");
			}
			catch
			{
				return View();
			}
		}

		public ActionResult List()
		{
			// Todo: Put this in a mapper
			NoteDao noteDao = new NoteDao();
			IList<Blt.Note> noteList = noteDao.GetNotes();

			IList<NoteViewModel> noteViewList = new List<NoteViewModel>();

			foreach (Blt.Note note in noteList)
			{
				NoteViewModel myNote = new NoteViewModel();
				myNote.NoteID = note.Id;
				myNote.Name = note.Name;
				myNote.Detail = note.Detail;
				myNote.Category = note.Category;

				noteViewList.Add(myNote);

			}

			return View(noteViewList);
			//return View();
		}
    }
}

Small.Data.Web/Views/Note/Create.cshtml
@model Small.Data.Web.Models.NoteViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Simple Note</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Detail)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Detail)
                @Html.ValidationMessageFor(model => model.Detail)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Category)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Category)
                @Html.ValidationMessageFor(model => model.Category)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Small.Data.Web/Views/Note/List.cshtml
@model IEnumerable<Small.Data.Web.Models.NoteViewModel>

@{
    ViewBag.Title = "List";
}

<p>
    @Html.ActionLink("Add Note", "Save")
</p>
<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Detail
        </th>
        <th>
            Category
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Detail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
@*            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.NoteID })
        </td>
    </tr>
}

</table>

Small.Data.Web/Views/Note/Save.cshtml
@{
    ViewBag.Title = "Save";
}

    <div ng-controller="NoteController">
        <legend>Note</legend>

        <div class="editor-label">
            Name
        </div>
        <div class="editor-field">
            <input type ="text" ng-model="note.name" class="form-control" />
        </div>

        <div class="editor-label">
            Detail
        </div>
        <div class="editor-field">
            @*<input type ="text" ng-model="note.detail" class="form-control" />*@
             <textarea class="form-control" rows="10" ng-model="note.detail"></textarea>
        </div>

         <div class="editor-label">
            Category
        </div>
        <div class="editor-field">
            <input type ="text" ng-model="note.category" class="form-control" />
        </div>

        <br />
        <p>
             <button class="btn btn-default" ng-click="save(note)" id="btnSave">Save Note</button>
        </p>
            <div style="color:red;" ng-show="error">An error occurred</div>
   </div>

@*<div>
    @Html.ActionLink("Back to List", "List", "Note")
</div>*@