Small.Data.Web/Models/MovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace Small.Data.Web.Models
{
	public class MovieViewModel
	{
		[Display(Name = "Title")]
		public string Title { get; set; }

		[Display(Name = "Release Date")]
		[DataType(DataType.DateTime)]
		[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime ReleaseDate { get; set; }

		[Display(Name = "Genre")]
		public string Genre { get; set; }
	}
}

Small.Data.Web/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Small.Data.Dat;
using Small.Data.Web.Models;

namespace Small.Data.Web.Controllers
{
    public class MovieController : Controller
    {
        //
        // GET: /Movie/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Movie/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Movie/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Movie/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Map this to the DAO
				Blt.Movie movie = new Blt.Movie();
				//movie.Title = collection.GetValue("title");
				movie.Title = Convert.ToString(collection["title"]);
				movie.Genre = Convert.ToString(collection["genre"]);
				movie.ReleaseDate = DateTime.Now;

				MovieDao movieDao = new MovieDao();
				movieDao.Insert(movie);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

		//
		// GET: /Movie/Save

		public ActionResult Save()
		{
			return View();
		} 

		[HttpPost]
		public ActionResult Save(MovieViewModel movie)
		{
			try
			{
				MovieDao movieDao = new MovieDao();
				Blt.Movie mov = new Blt.Movie();

				mov.Title = movie.Title;
				mov.Genre = movie.Genre;
				mov.ReleaseDate = DateTime.Now;
				movieDao.Insert(mov);

				return RedirectToAction("List");
			}
			catch
			{
				return View();
			}
			//return new HttpStatusCodeResult(HttpStatusCode.OK);
		}

        //
        // GET: /Movie/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Movie/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Movie/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Movie/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

		//
		// GET: /Movie/List

		public ActionResult List()
		{
			// Todo: Put this in a mapper
			MovieDao movieDao = new MovieDao();
			IList<Blt.Movie> movieList = movieDao.GetMovies();

			IList<MovieViewModel> movieViewList = new List<MovieViewModel>();

			foreach (Blt.Movie movie in movieList)
			{
				MovieViewModel mov = new MovieViewModel();
				mov.Title = movie.Title;
				mov.Genre = movie.Genre;
				mov.ReleaseDate = movie.ReleaseDate;

				movieViewList.Add(mov);
			}

			return View(movieViewList);
			//return View();
		}
    }
}

Small.Data.Web/Views/Movie/Create.cshtml
@model Small.Data.Web.Models.MovieViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Movie</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseDate)
            @Html.ValidationMessageFor(model => model.ReleaseDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Genre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Genre)
            @Html.ValidationMessageFor(model => model.Genre)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Small.Data.Web/Views/Movie/List.cshtml
@model IEnumerable<Small.Data.Web.Models.MovieViewModel>

@{
    ViewBag.Title = "List";
}

<p>
    @Html.ActionLink("Create New", "Save")
</p>
<table>
    <tr>
        <th>
            Title
        </th>
        <th>
            Release Date
        </th>
        <th>
            Genre
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate, "{0:d}")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
@*        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

Small.Data.Web/Views/Movie/Save.cshtml
@{
    ViewBag.Title = "Save";
}

    <div ng-controller="MovieController">
        <legend>Movie</legend>

        <div class="editor-label">
            Title
        </div>
        <div class="editor-field">
            <input type ="text" ng-model="movie.title" class="form-control" />
        </div>

        <div class="editor-label">
            Release Date
        </div>
        <div class="editor-field">
            <input type ="date" ng-model="movie.releasedate" class="form-control" placeholder="The release date of the movie"/>
        </div>

        <div class="editor-label">
            Genre
        </div>
        <div class="editor-field">
            <input type ="text" ng-model="movie.genre" class="form-control" />
        </div>
        <br />
        <p>
             <button class="btn btn-default" ng-click="save(movie)" id="btnSave">Save Movie</button>
        </p>
            <div style="color:red;" ng-show="error">An error occurred</div>
   </div>

<div>
    @Html.ActionLink("Back to List", "List", "Movie")
</div>